### ISSUE TITLE
Question not an issue

### ISSUE THREAD

**Issue by maheraldous** [Globobeet/keystone-cloudinary-gallery-field#4]
Hello

Thanks for this amazing work. I wonder if there is something like that with file upload but as gallery not just single file upload like in default KeystoneJS?

Thanks in advance.

**Comment by joshlasdin** [comment]
@maheraldous Thanks for the kind words! Apologies for responding to this an embarrassing 2 months later, just had my first child about a month ago and things have been crazy. I'm not aware of anything in the KS ecosystem right now that would do this kind of functionality with file uploads. It's definitely a feature we had considering for this plugin but chopped it in the interest of getting the plugin out (which we needed for some of our own projects). Adding file uploads is a sensible future feature, but at this point we don't have any sort of timeline for that.
